targets:
  $default:
    builders:
      # Generate MobX files
      mobx_codegen:
        options:
          # This is the directory where your .g.dart files will be generated
          output_dir: lib/stores