name: aichat
description: aichat

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_markdown: ^0.6.14
  uuid: ^3.0.7
  http: ^0.13.5
  sp_util: ^2.0.3
  shared_preferences: ^2.0.20
  intl: ^0.18.0
  dart_openai: ^1.9.1
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.10
  share_plus: ^6.3.1
  rating_dialog: ^2.0.4
  lottie: ^2.3.1
  provider: ^6.0.5
  flutter_tts: ^3.6.3
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  photo_view: ^0.14.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_dotenv: ^5.0.2

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
    - assets/
    - assets/images/
  fonts: 
    - family: Abel
      fonts: 
        - asset: assets/fonts/AbelRegular.ttf
          weight: 400